const $=id=>document.getElementById(id);
let loginMode=true;
let toastTimer;
const toast=m=>{const t=$('toast');t.textContent=m;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2600)};
const setBusy=(el,busy,text)=>{if(!el)return;el.disabled=busy;el.classList.toggle('busy',busy);if(text&&el.querySelector('span'))el.querySelector('span').textContent=text};
function setAuth(mode){loginMode=mode;$('authTitle').textContent=mode?'ورود به حساب':'ساخت حساب';$('authSubtitle').textContent=mode?'وارد پنل شخصی ساخت و مدیریت کانفیگ شو.':'حساب بساز و کانفیگ‌هایت را یکجا مدیریت کن.';$('usernameLabel').classList.toggle('hidden',mode);$('username').required=!mode;$('login').placeholder=mode?'ایمیل یا نام کاربری':'example@mail.com';$('password').autocomplete=mode?'current-password':'new-password';$('authSubmit').querySelector('span').textContent=mode?'ورود':'ثبت‌نام';$('switchAuth').innerHTML=mode?'حساب نداری؟ <b>ثبت‌نام</b>':'قبلاً حساب داری؟ <b>ورود</b>';$('authError').textContent=''}
async function api(path,options={}){const r=await fetch(path,{credentials:'include',...options,headers:{'content-type':'application/json',...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'خطایی رخ داد');return d}
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const copyText=async text=>{try{await navigator.clipboard.writeText(text)}catch{const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove()}};
function configParams(){const transport=$('transport').value,tls=$('tls').value,params=new URLSearchParams({type:transport,security:tls});if(transport==='ws'){params.set('path',$('wsPath').value.trim()||'/');const host=$('wsHost').value.trim();if(host)params.set('host',host)}if(transport==='grpc'){const service=$('grpcService').value.trim();if(service)params.set('serviceName',service)}return params}
function updateTransportFields(){const t=$('transport').value;$('wsFields').classList.toggle('hidden',t!=='ws');$('grpcFields').classList.toggle('hidden',t!=='grpc')}
function renderConfigs(configs){$('configCount').textContent=configs.length;$('configCount2').textContent=configs.length;$('configList').innerHTML=configs.map(c=>`<article class="config-item"><div class="config-row"><div><b>${escapeHtml(c.name)}</b><small>${escapeHtml(c.created_at||'ذخیره‌شده')}</small></div><div><button class="mini-btn" type="button" data-copy-id="${escapeHtml(c.id)}">کپی</button><button class="mini-btn danger" type="button" data-delete="${escapeHtml(c.id)}">حذف</button></div></div><small class="config-data">${escapeHtml(c.data)}</small></article>`).join('')||'<div class="empty-state"><div>◇</div><b>هنوز کانفیگی ساخته نشده</b><span>از بخش ساخت کانفیگ، اولین موردت را ایجاد کن.</span></div>';$('configList').querySelectorAll('[data-copy-id]').forEach(b=>b.onclick=async()=>{const c=configs.find(x=>String(x.id)===b.dataset.copyId);if(c){await copyText(c.data);toast('کانفیگ کپی شد')}});$('configList').querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('این کانفیگ حذف شود؟'))return;try{await api('/api/configs/'+encodeURIComponent(b.dataset.delete),{method:'DELETE'});await loadConfigs();toast('کانفیگ حذف شد')}catch(e){toast(e.message)}})}
async function loadConfigs(){try{const d=await api('/api/configs');renderConfigs(d.configs||[])}catch(e){if(e.message!=='Unauthorized')toast(e.message)}}
async function enterApp(user){$('authView').classList.add('hidden');$('appView').classList.remove('hidden');$('welcomeUser').textContent=user.username;$('profileName').textContent=user.username;$('profileEmail').textContent=user.email;$('profileAvatar').textContent=(user.username||'U').slice(0,1).toUpperCase();await loadConfigs()}
async function check(){try{const d=await api('/api/auth/me');if(d.user)await enterApp(d.user)}catch(_){} }
$('authForm').addEventListener('submit',async e=>{e.preventDefault();$('authError').textContent='';const btn=$('authSubmit');setBusy(btn,true,'در حال بررسی...');try{const body=loginMode?{login:$('login').value.trim(),password:$('password').value}:{username:$('username').value.trim(),email:$('login').value.trim(),password:$('password').value};const d=await api(loginMode?'/api/auth/login':'/api/auth/register',{method:'POST',body:JSON.stringify(body)});await enterApp(d.user)}catch(err){$('authError').textContent=err.message}finally{setBusy(btn,false,loginMode?'ورود':'ثبت‌نام')}});
$('switchAuth').addEventListener('click',()=>setAuth(!loginMode));
$('logout').addEventListener('click',async()=>{try{await api('/api/auth/logout',{method:'POST'})}finally{location.reload()}});
$('configForm').addEventListener('submit',async e=>{e.preventDefault();const btn=e.submitter||$('configForm').querySelector('button[type=submit]');try{const name=$('configName').value.trim(),server=$('serverAddress').value.trim(),port=$('serverPort').value.trim(),uuid=$('uuid').value.trim();if(!name||!server||!port||!uuid)throw new Error('اطلاعات را کامل وارد کن');if(!/^\d{1,5}$/.test(port)||+port<1||+port>65535)throw new Error('پورت باید بین 1 تا 65535 باشد');const output=`vless://${encodeURIComponent(uuid)}@${server}:${port}?${configParams().toString()}#${encodeURIComponent(name)}`;$('generatedText').value=output;$('generated').classList.remove('hidden');setBusy(btn,true,'در حال ذخیره...');await api('/api/configs',{method:'POST',body:JSON.stringify({name,data:output})});await loadConfigs();toast('کانفیگ ساخته و ذخیره شد');$('generated').scrollIntoView({behavior:'smooth',block:'nearest'})}catch(err){toast(err.message)}finally{setBusy(btn,false,'تولید و ذخیره کانفیگ')}});
$('copyConfig').addEventListener('click',async()=>{const text=$('generatedText').value;if(!text)return;await copyText(text);toast('کانفیگ کپی شد')});$('newConfig').addEventListener('click',()=>{$('builder').scrollIntoView({behavior:'smooth'});setTimeout(()=>$('configName').focus(),450)});$('transport').addEventListener('change',updateTransportFields);
document.querySelectorAll('[data-section]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();document.querySelectorAll('nav a').forEach(x=>x.classList.remove('active'));a.classList.add('active');document.getElementById(a.dataset.section)?.scrollIntoView({behavior:'smooth',block:'start'})}));
const sections=['dashboard','builder','configs'].map(id=>document.getElementById(id));const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){const link=document.querySelector(`[data-section="${entry.target.id}"]`);if(link){document.querySelectorAll('nav a').forEach(x=>x.classList.remove('active'));link.classList.add('active')}}}),{rootMargin:'-25% 0px -65%'});sections.forEach(s=>s&&observer.observe(s));
setAuth(true);updateTransportFields();check();