const json=(data,status=200,extra={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8',...extra}});
const sessionCookie=(id,maxAge)=>`session=${id}; Max-Age=${maxAge}; Path=/; HttpOnly; Secure; SameSite=Strict`;
const token=request=>request.headers.get('Cookie')?.match(/(?:^|; )session=([^;]+)/)?.[1];
async function hashPassword(password){const data=new TextEncoder().encode(password);const hash=await crypto.subtle.digest('SHA-256',data);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('');}
async function currentUser(request,env){const id=token(request);if(!id||!env.DB)return null;return await env.DB.prepare('SELECT id, username, email FROM users WHERE id = ?').bind(id).first();}
const cleanConfig=(body)=>{const name=String(body.name||'').trim();const data=typeof body.data==='string'?body.data:JSON.stringify(body.data??{});const volumeGb=Number(body.volumeGb);const days=Number(body.days);const location=String(body.location||'').trim().slice(0,50);if(!name||name.length>100||data.length>5000||!Number.isInteger(volumeGb)||volumeGb<1||volumeGb>10000||!Number.isInteger(days)||days<1||days>3650||!location)return null;const expiresAt=new Date(Date.now()+days*86400000).toISOString();return{name,data,volumeGb,days,location,expiresAt};};
const ensureMeta=async env=>{await env.DB.prepare(`CREATE TABLE IF NOT EXISTS config_meta (config_id TEXT PRIMARY KEY,user_id TEXT NOT NULL,volume_gb INTEGER NOT NULL DEFAULT 1,used_bytes INTEGER NOT NULL DEFAULT 0,location TEXT NOT NULL DEFAULT '',expires_at TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')),FOREIGN KEY(config_id) REFERENCES configs(id) ON DELETE CASCADE,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE)`).run();};
const metaStatus=m=>{const expired=m?.expires_at&&Date.parse(m.expires_at)<=Date.now();const limit=m?.volume_gb>0&&Number(m?.used_bytes||0)>=Number(m.volume_gb)*1024*1024*1024;return expired?'expired':limit?'limit':'active';};
async function providerRequest(env,path,body){if(!env.PROVIDER_API_URL)return null;const base=env.PROVIDER_API_URL.replace(/\\/$/,'');const headers={'content-type':'application/json'};if(env.PROVIDER_API_KEY)headers.authorization=`Bearer ${env.PROVIDER_API_KEY}`;const r=await fetch(`${base}${path}`,{method:'POST',headers,body:JSON.stringify(body)});const t=await r.text();let data;try{data=JSON.parse(t)}catch(_){data={raw:t}}if(!r.ok)throw new Error(data?.error||`Provider HTTP ${r.status}`);return data;};
export default{async fetch(request,env){const url=new URL(request.url);
if(url.pathname==='/api/health'){let database=false;if(env.DB){try{await env.DB.prepare('SELECT 1').first();database=true;}catch(_){}}return json({ok:true,service:'config-web',database,provider:!!env.PROVIDER_API_URL});}
if(url.pathname==='/api/provider/status'&&request.method==='GET')return json({configured:!!env.PROVIDER_API_URL,apiKeyConfigured:!!env.PROVIDER_API_KEY});
if(url.pathname==='/api/auth/register'&&request.method==='POST'){if(!env.DB)return json({error:'Database unavailable'},503);let body;try{body=await request.json();}catch(_){return json({error:'Invalid JSON'},400)}const username=String(body.username||'').trim(),email=String(body.email||'').trim().toLowerCase(),password=String(body.password||'');if(!/^[a-zA-Z0-9_]{3,30}$/.test(username)||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||password.length<8)return json({error:'Invalid registration data'},400);const exists=await env.DB.prepare('SELECT id FROM users WHERE username=? OR email=?').bind(username,email).first();if(exists)return json({error:'Username or email already exists'},409);const id=crypto.randomUUID();await env.DB.prepare('INSERT INTO users(id,username,email,password_hash) VALUES(?,?,?,?)').bind(id,username,email,await hashPassword(password)).run();return json({user:{id,username,email}},201,{'Set-Cookie':sessionCookie(id,604800)});}
if(url.pathname==='/api/auth/login'&&request.method==='POST'){if(!env.DB)return json({error:'Database unavailable'},503);let body;try{body=await request.json()}catch(_){return json({error:'Invalid JSON'},400)}const login=String(body.login||'').trim().toLowerCase(),passwordHash=await hashPassword(String(body.password||''));const user=await env.DB.prepare('SELECT id,username,email,password_hash FROM users WHERE lower(username)=? OR lower(email)=?').bind(login,login).first();if(!user||user.password_hash!==passwordHash)return json({error:'Invalid credentials'},401);return json({user:{id:user.id,username:user.username,email:user.email}},200,{'Set-Cookie':sessionCookie(user.id,604800)});}
if(url.pathname==='/api/auth/me'){const user=await currentUser(request,env);return user?json({user}):json({user:null},401)}
if(url.pathname==='/api/auth/logout'&&request.method==='POST')return json({ok:true},200,{'Set-Cookie':sessionCookie('',0)});
if(url.pathname==='/api/configs'&&request.method==='GET'){const user=await currentUser(request,env);if(!user)return json({error:'Unauthorized'},401);await ensureMeta(env);const rows=await env.DB.prepare('SELECT c.id,c.name,c.data,c.created_at,m.volume_gb,m.used_bytes,m.location,m.expires_at FROM configs c LEFT JOIN config_meta m ON m.config_id=c.id WHERE c.user_id=? ORDER BY c.created_at DESC LIMIT 100').bind(user.id).all();const configs=(rows.results??[]).map(c=>({...c,status:metaStatus(c)}));return json({configs});}
if(url.pathname==='/api/configs'&&request.method==='POST'){const user=await currentUser(request,env);if(!user)return json({error:'Unauthorized'},401);let body;try{body=await request.json()}catch(_){return json({error:'Invalid JSON'},400)}const config=cleanConfig(body);if(!config)return json({error:'Invalid config data'},400);await ensureMeta(env);const id=crypto.randomUUID();let providerData=null;if(env.PROVIDER_API_URL){try{providerData=await providerRequest(env,'/configs',{id,userId:user.id,name:config.name,volumeGb:config.volumeGb,days:config.days,location:config.location});}catch(error){return json({error:'Provider request failed',details:error.message},502);}}const finalData=providerData?.data||config.data;await env.DB.prepare('INSERT INTO configs(id,user_id,name,data) VALUES(?,?,?,?)').bind(id,user.id,config.name,finalData).run();await env.DB.prepare('INSERT INTO config_meta(config_id,user_id,volume_gb,location,expires_at) VALUES(?,?,?,?,?)').bind(id,user.id,config.volumeGb,config.location,config.expiresAt).run();return json({id,...config,data:finalData,status:'active',usedBytes:0,provider:!!providerData},201);}
if(url.pathname.startsWith('/api/configs/')&&request.method==='PUT'){const user=await currentUser(request,env);if(!user)return json({error:'Unauthorized'},401);const id=url.pathname.split('/').pop();if(!id)return json({error:'Invalid config id'},400);let body;try{body=await request.json()}catch(_){return json({error:'Invalid JSON'},400)}const config=cleanConfig(body);if(!config)return json({error:'Invalid config data'},400);await ensureMeta(env);const result=await env.DB.prepare('UPDATE configs SET name=?,data=? WHERE id=? AND user_id=?').bind(config.name,config.data,id,user.id).run();if(!result.meta?.changes)return json({error:'Config not found'},404);await env.DB.prepare('UPDATE config_meta SET volume_gb=?,location=?,expires_at=? WHERE config_id=? AND user_id=?').bind(config.volumeGb,config.location,config.expiresAt,id,user.id).run();return json({id,...config});}
if(url.pathname.startsWith('/api/configs/')&&request.method==='DELETE'){const user=await currentUser(request,env);if(!user)return json({error:'Unauthorized'},401);const id=url.pathname.split('/').pop();if(!id)return json({error:'Invalid config id'},400);const result=await env.DB.prepare('DELETE FROM configs WHERE id=? AND user_id=?').bind(id,user.id).run();if(!result.meta?.changes)return json({error:'Config not found'},404);await ensureMeta(env);await env.DB.prepare('DELETE FROM config_meta WHERE config_id=? AND user_id=?').bind(id,user.id).run();return json({ok:true});}
if(url.pathname.startsWith('/api/'))return json({error:'Not found'},404);return env.ASSETS.fetch(request);}};